version: '3.8'

services:
  mindmap-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mindmap-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - ./node_modules/app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - api-backend
    networks:
      - mindmap-network
    command: sh -c "npm i && npx vue-cli-service serve --port 8080 --host 0.0.0.0"

  api-backend:
    build:
      context: ./api
      target: development
    container_name: mindmap-api
    #command: sh -c "go mod tidy && go build -o main . && ./main"
    command: air
    environment:
      PORT: 8000
      LOG_LEVEL: info
      POSTGRES_HOST: postgres
      POSTGRES_DB: mindmap_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      APP_PACKAGE_NAME: github.com/mymindmap/api
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mindmap-network
    volumes:
      - ./api:/app

  caddy:
    image: caddy
    container_name: mindmap-caddy
    depends_on:
      - api-backend
      - mindmap-frontend
    ports:
      - 80:80
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./api/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - mindmap-network

  postgres:
    image: postgres:bookworm
    restart: always
    container_name: mindmap-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mindmap_db
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U postgres -d mindmap_db'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mindmap-network

  # migrate:
  #   image: migrate/migrate
  #   container_name: mindmap-migrate
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - mindmap-network
  #   volumes:
  #     - ./api/repository/migrations/:/migrations
  #   command: ["-path", "/migrations/", "-database", "postgres://postgres:password@postgres/mindmap_db?sslmode=disable", "up"]

volumes:
  postgres-data:
  caddy-config:
  caddy-data:

networks:
  mindmap-network:
    driver: bridge