root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o bin/server ./cmd/server"
bin = "./bin/server"
full_bin = ""
log = "build-errors.log"
pre_cmds = ["go mod tidy"]

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules", "temp","pkg/example"]
